name: Deploy Action
on: [push]
jobs:
  Deploy-to-AWS-on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the repo.
        uses: actions/checkout@v3
        env: |
          AWS_DEFAULT_REGION=ap-south-1
      - name: Setup Python
        uses: actions/setup-python@v4.1.0
        with:
          python-version: '3.10'
#       - name: Installing AWS Cli
#         shell: bash
#         run: |
#           sudo apt update
#           sudo apt install awscli
#       - name: Configure AWS Credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: ap-south-1
      - name: Installing the packages
        run: pip install -r requirements.txt
      - name: Running unittest
        run: coverage run --source=lambdas -m pytest -s -v
      - name: Checking coverage
        run: coverage report --fail-under=80
#      - name: HashiCorp - Setup Terraform
#        uses: hashicorp/setup-terraform@v2.0.0
#      - name: Terraform Init
#        id: init
#        run: terraform init
#      - name: Terraform Plan
#        id: plan
#        run: terraform plan
#      - name: Terraform apply
#        id: apply
#        run: terraform apply -auto-approve
#      - name: Sleep for 60 seconds
#        run: sleep 60s
#        shell: bash
#      - name: Terraform Destroy
#        id: destroy
#        run: terraform destroy -auto-approve
      - run: echo "Job completed."
