name: Deploy Action
on: workflow_dispatch
jobs:
  Running-Unit-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the repo.
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4.1.0
        with:
          python-version: '3.10'
      - name: Installing AWS Cli
        shell: bash
        run: |
          sudo apt update
          sudo apt install awscli
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: Installing the packages
        shell: bash
        run: |
          pip install -r requirements.txt
          pwd
          export PYTHONPATH=$PYTHONPATH:/home/runner/work/aws_terraform/aws_terraform/lambdas
      - name: Running unittest
        run: coverage run --source=lambdas -m pytest -s -v
      - name: Checking coverage
        run: coverage report --fail-under=80
  Deploying-to-AWS:
    needs: Running-Unit-Test
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the repo.
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4.1.0
        with:
          python-version: '3.10'
      - name: Installing AWS Cli
        shell: bash
        run: |
          sudo apt update
          sudo apt install awscli
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.0
      - name: Changing directory
        run: cd terraform_files
      - name: Terraform Init
        id: init
        run: terraform init
      - name: Terraform Plan
        id: plan
        run: terraform plan
      - name: Terraform apply
        id: apply
        run: terraform apply -auto-approve
  Running-Behave-Tests:
    needs: [Running-Unit-Test,Deploying-to-AWS]
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the repo.
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4.1.0
        with:
          python-version: '3.10'
      - name: Installing AWS Cli
        shell: bash
        run: |
          sudo apt update
          sudo apt install awscli
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: Installing the packages
        run: pip install -r requirements.txt
      - name: Running behave test
        run: behave
      - name: Terraform Init
        id: init
        run: terraform init
      - name: Terraform Destroy
        id: destroy
        run: terraform destroy -auto-approve
      - run: echo "Job completed."
