name: Deploy Action
on: [push]
jobs:
  Deploy-to-AWS-on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the repo.
        uses: actions/checkout@v3
      - name: Setup AWS SAM CLI
        shell: bash
        run: |
          sudo apt update
          sudo apt install awscli
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.0
      - name: Terraform Init
        id: init
        run: terraform init
      - name: Terraform Plan
        id: plan
        run: terraform plan
      - name: Terraform apply
        id: apply
        run: terraform apply -auto-approve
      - name: Sleep for 30 seconds
        run: sleep 120s
        shell: bash
      - name: Terraform Destroy
        id: destroy
        run: terraform destroy -auto-approve
      - run: echo "Job completed."
